### ISSUE TITLE
Update content for CP4D 4.7

### ISSUE THREAD

**Issue by seansund** [IBM/credit-risk-workshop-cpd#146]
## Workshop

- [x] Main page (cloud-native-toolkit/credit-risk-workshop-cpd#1)
- [x] Pre-work (cloud-native-toolkit/credit-risk-workshop-cpd#1)
- [x] Data Connection and Virtualization (cloud-native-toolkit/credit-risk-workshop-cpd#1)
- [x] Import Data to Project (cloud-native-toolkit/credit-risk-workshop-cpd#1)
- [x] Data Visualization with Data Refinery (cloud-native-toolkit/credit-risk-workshop-cpd#1)
- [x] Enterprise data governance for Viewers using Watson Knowledge Catalog (cloud-native-toolkit/credit-risk-workshop-cpd#2)
- [ ] Enterprise data governance for Admins using Watson Knowledge Catalog
- [x] Machine Learning with Jupyter (cloud-native-toolkit/credit-risk-workshop-cpd#3)
- [x] Machine Learning with AutoAI (cloud-native-toolkit/credit-risk-workshop-cpd#4)
- [x] Deploy and Test Machine Learning Models (cloud-native-toolkit/credit-risk-workshop-cpd#6)
- [ ] Monitoring models with OpenScale GUI (Auto setup Monitoring)
- [ ] Monitoring models with OpenScale (Notebook)

## Admin steps

- [ ] Main page
- [ ] Configure Cloud Pak for Data
- [ ] Create/Load Database
- [ ] Configure Database Connections
- [ ] Configure Data Virtualization
- [ ] Configure Watson Knowledge Catalog
- [ ] Configure Watson OpenScale
